name: First Github Workflow Group
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          echo "Hello World"
          echo "We will start soon!"
      - name: Print goodbye
        run: echo "Done! Bye!"
